{{- if not .Values.installByPlacement.placementName }}
apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  name: global
  namespace: {{ .Release.Namespace }}
spec:
  clusterSet: global
{{- end }}
