apiVersion: proxy.open-cluster-management.io/v1alpha1
kind: ManagedProxyConfiguration
metadata:
  name: cluster-proxy
spec:
  authentication:
    dump:
      secrets: {}
    signer:
      type: SelfSigned
  proxyServer:
    image: {{ .Values.proxyServerImage }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
    replicas: {{ .Values.replicas }}
    namespace: {{ .Release.Namespace }}
    entrypoint:
      {{- if .Values.proxyServer.entrypointAddress }}
      type: Hostname
      hostname:
        value: {{ .Values.proxyServer.entrypointAddress }}
        port: {{ .Values.proxyServer.port }}
      {{- else if .Values.proxyServer.entrypointLoadBalancer }}
      type: LoadBalancerService
      loadBalancerService: {}
      {{- else  }}
      type: PortForward
      {{- end }}
      port: {{ .Values.proxyServer.port }}
  proxyAgent:
    image: {{ .Values.proxyAgentImage }}:{{ .Values.tag | default (print "v" .Chart.Version) }}
    replicas: {{ .Values.replicas }}
    additionalValues:
      enableImpersonation: {{ .Values.enableImpersonation | quote }}
  {{- if .Values.userServer.enabled }}
  userServer:
    {{- if .Values.userServer.namespace }}
    namespace: {{ .Values.userServer.namespace }}
    {{- end }}
    serviceName: {{ .Values.userServer.serviceName }}
    {{- if .Values.userServer.additionalSANs }}
    additionalSANs:
      {{- toYaml .Values.userServer.additionalSANs | nindent 6 }}
    {{- end }}
  {{- end }}
