apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: cluster-proxy-addon-manager
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      open-cluster-management.io/addon: cluster-proxy
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: cluster-proxy
    spec:
      serviceAccount: cluster-proxy
      containers:
        - name: manager
          image: {{ .Values.registry }}/{{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: IfNotPresent
          command:
            - /manager
          args:
            - --leader-elect=true
            - --signer-secret-namespace={{ .Release.Namespace }}
